### ISSUE TITLE
Better way to implement

### ISSUE THREAD

**Issue by arrudagates** [rubenkharel/README-VSCODE-Automation#1]
A better way to do this and avoid commit spamming would be to dynamically pull an image from an external source, like how they make spotify now playing cards here: https://github.com/kittinan/spotify-github-profile

**Comment by rubenkharel** [comment]
I thought of that, but I lack skills. That's why I am thinking of doing it in the future in v1. But I was wondering If I can use Github Action to delete the past commits every time there is a new commit. Even if that's possible it's not a efficient way to do it. But just finding out the alternative till I got some skills and time to make it similar to Spotify.
